#!/bin/bash
#--------------------Author:ekahPruthvi--------------------#
Center_text() {
    local ctext="$1"
    local cwidth=$(tput cols)
    local cpadding=$(( (cwidth - ${#ctext}) / 2 ))
    printf "%${cpadding}s%s \n" "" "$ctext"
}

if [ $# -eq 0 ]; then
    Center_text "Basil - UI for The Terminal"
    Center_text "The is a help message"
    printf "Usage:\n"
    printf "    cook [option] <file.pesto>\n"
    printf "\noptions:\n"
    printf "(Leave options plain for default)\n"
    printf "    -r - retro mode\n"
    printf "    -b - black and white\n" 

elif [ $# -eq 1 ]; then
    if [ "$1" == "-del" ]; then
        printf "DO YOU WANT TO UNINSTALL BASIL?(Y/N)"
        read inp
        case $inp in
            Y) printf "\nUNCOOKING pastas\n" 
               sudo rm /opt/pasta && sudo rm /usr/bin/cook;;
            N) printf "\nThe pastas are safe\n";;
            *) echo "invalid input" ;; 
        esac
    fi
    basil="/opt/pasta/basil"
    pesto="$1"
    cat $basil > ui.sh
    echo "" >> ui.sh
    cat $pesto >> ui.sh
    chmod +x ui.sh
else
    if [ "$1" == "-r" ]; then
        basil="/opt/pasta/ancient_basil"
        pesto="$2"
        cat $basil > ui.sh
        echo "" >> ui.sh
        cat $pesto >> ui.sh
        chmod +x ui.sh
    fi
    if [ "$1" == "-b" ]; then
        basil="/opt/pasta/chess_basil" 
        pesto="$2"
        cat $basil > ui.sh
        echo "" >> ui.sh
        cat $pesto >> ui.sh
        chmod +x ui.sh
    fi
fi
